FROM node as build-stage

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

ARG REACT_APP_NAME

ENV REACT_APP_NAME=$REACT_APP_NAME

RUN npm run build

FROM nginx

COPY --from=build-stage /app/build /usr/share/nginx/html